### PR TITLE
Fixes Problem parsing date with offset #4 - parse with or without zone w...

### PR DESCRIPTION
**Pull request by davidkarlsen**
...hich is aligned with xsd:date

### CODE REVIEW

**Comment by davidkarlsen** [comment]
Great - thanks! Would you mind doing a release as well?

**Comment by migesok** [comment]
Sure, I'll do it tomorrow.

**Comment by migesok** [comment]
Done.
Check out 1.1.3 version.

**Comment by davidkarlsen** [comment]
Already have - thanks! :)

**Pull request merged**
